services:
    laravel-docker:
        container_name: kurikulum-app
        build: .
        volumes:
            - .:/var/www/html
        ports:
            - 80:80

    mysql_db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 8080:8080
        environment:
            - PMA_ARBITRARY=1
